- name: Vars inventory vars_files
  hosts: local
  connection: local
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: Hello, {{ COURSE }} course duration {{ DURATION}} trainser is{{ TRAINER }}

